CREATE TABLE Card
(
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    card_type INT NOT NULL FOREIGN KEY REFERENCES CardType(id),
    link VARCHAR NOT NULL UNIQUE FOREIGN KEY REFERENCES Link(link),
    video_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Video(ID)
)