CREATE TABLE Join
(
    joined_to_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Channel(ID),
    joiner_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Channel(ID) --baska isim gelmedi aklima,
    joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    join_type INT NOT NULL FOREIGN KEY REFERENCES JoinTypes(ID),
)