CREATE TABLE ShortsCategory
(
    ID INT NOT NULL IDENTITY(1,1),
    shorts_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Shorts(ID),
    category_ID INT NOT NULL FOREIGN KEY REFERENCES Category(ID),

)