CREATE TABLE VideoAnalytics
(
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    video_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Video(ID),
    like_count INT NOT NULL DEFAULT 0,
    dislike_count INT NOT NULL DEFAULT 0,
    country_ID INT NOT NULL FOREIGN KEY REFERENCES Country(ID),
    click_ratio INT NOT NULL DEFAULT 0,
)