CREATE TABLE Card
(
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    card_type INT NOT NULL FOREIGN KEY REFERENCES CardType(ID),
    link VARCHAR(255) NOT NULL UNIQUE FOREIGN KEY REFERENCES VideoLink(link),
    video_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Video(ID)
)
