CREATE TABLE Subtitle
(
    ID UNIQUEIDENTIFIER  DEFAULT newid() NOT NULL PRIMARY KEY,
    video_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Video(ID),
    language_ID INT NOT NULL FOREIGN KEY REFERENCES Languages(ID),
    subtitle TEXT NOT NULL,
)
