CREATE TABLE Shorts
(
    ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    channel_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Channel(ID),
    title VARCHAR(255) NOT NULL DEFAULT GETDATE(),
    privacy_ID INT NOT NULL FOREIGN KEY REFERENCES Privacy(ID)
)
