CREATE TABLE Video 
(
   ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
   channelID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Channel(ID), 
   title VARCHAR NOT NULL DEFAULT GETDATE(),
   createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   likes INT NOT NULL DEFAULT 0 ,
   countryID INT NOT NULL FOREIGN KEY REFERENCES Country(ID)
   --description FK farkli tablodan gelicek (buyuk data)
)
