CREATE TABLE Video 
(
   ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
   channel_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Channel(ID), 
   title VARCHAR NOT NULL DEFAULT GETDATE(),
   createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   likes INT NOT NULL DEFAULT 0 ,
   country_ID INT NOT NULL FOREIGN KEY REFERENCES Country(ID)
   privacy INT NOT NULL FOREIGN KEY REFERENCES Privacy(ID)
   --description FK farkli tablodan gelicek (buyuk data)
)
